backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: img
public_folder: pup
collections:
  - name: "information"
    label: "Information"
    files:
      - label: "Blogs"
        name: "blogs"
        file: "cdn.json"
        fields:
          - { label: "Title", name: "Title", widget: "string" }
          - { label: "Layout" , name: "Layout", widget: "markdown" }
          - label: "Featured Image"
            name: "thumbnail"
            widget: "image"
            choose_url: true

